export const toUpperLabel = {
    list: 'LISTA',
    listOf: 'LISTA DE ',
    create: 'CREAR ',
    detail: 'DETALLE ',
    search: 'BUSCAR ',
    exercises: 'EJERCICIOS',
    exercise: 'EJERCICIO',
    muscle: 'MÚSCULO',
    muscles: 'MÚSCULOS',
    user: 'USUARIO',
    users: 'USUARIOS',
    rutine: 'RUTINA',
    rutines: 'RUTINAS',
    time: 'TIEMPO',
    description: 'DESCRIPCIÓN',
    profile: 'PERFIL',
    noExist: 'NO EXISTEN ',
    day: 'DÍA',
    days: 'DÍAS',
    period: 'PERÍODO',
    periodOf: 'PERÍODO DE ',
    cout: 'CANTIDAD',
    countOf: 'CANTIDAD DE ',
    new: 'NUEVO ',
    newA: 'NUEVA ',
    continue: 'CONTINUAR',
    select: 'SELECCIONAR ',
    session: 'SESIÓN',
    closer: 'CERRAR',
    start: 'INICIAR ',
    save: 'GUARDAR ',
    delete: 'BORRAR',
    arm: 'ARMAR ',
    serie: 'SERIE',
    series: 'SERIES',
    created: 'CREADO',
    createdA: 'CREADA'
}

export const toLowerLabel = {
    list: 'Lista',
    listOf: 'Lista de ',
    create: 'Crear ',
    detail: 'Detalle de ',
    search: 'Buscar ',
    exercises: 'Ejercicios',
    exercise: 'Ejercicio',
    muscle: 'Músculo',
    muscles: 'Músculos',
    user: 'Usuario',
    users: 'Usuarios',
    rutine: 'Rutina',
    rutines: 'Rutinas',
    time: 'Tiempo',
    description: 'Descripción',
    profile: 'Perfil',
    noExist: 'No existe ',
    day: 'Día',
    days: 'Días',
    period: 'Período',
    periodOf: 'Período de ',
    cout: 'Cantidad',
    countOf: 'Cantidad de ',
    new: 'Nuevo ',
    c: 'Nueva ',
    continue: 'Continuar',
    select: 'Seleccionar ',
    session: 'Sesión',
    closer: 'Cerrar ',
    start: 'Iniciar',
    save: 'Guardar',
    delete: 'Borrar',
    arm: 'Armar ',
    serie: 'Serie',
    series: 'Series',
    created: 'Creado',
    createdA: 'Creada'
}